export const LOAD_SAVED = 'LOAD_SAVED';
export const ADD_PRODUCT_TO_SAVED = 'ADD_PRODUCT_TO_SAVED';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const UPDATE_CART = 'UPDATE_CART';
